---
title: "R Notebook"
output: html_notebook
---

## You can borrow the data loading section from the file "Get_metric.Rmd"

```{r}
library(harmony)
library(Matrix)
#setwd("Your_workpath")
```


### Creating Harmony object
```{r}
V <- cell_lines$scaled_pcs
meta_data <- cell_lines$meta_data

harmonyObj <- RunHarmony(
    data_mat = V, 
    meta_data = meta_data, 
    theta = 1, 
    vars_use = 'dataset', 
    nclust = 50, ## number of clusters in Harmony model
    max_iter = 0,
    return_object = TRUE ## return the full Harmony model object, not just the corrected PCA matrix
)
```


### Running harmony
```{r}
for (i in 1:3) {
    harmony:::harmonize(harmonyObj, 1)
}
```


### Saving
```{r}
embedding <- t(harmonyObj$Z_cos)
rownames(embedding) <- cell_lines$meta_data$cell_id

write.csv(embedding, file = "harmony_embedding.csv", quote = FALSE)

write.csv(cell_lines$metadata, file = "harmony_metadata.csv", quote = FALSE, row.names = TRUE)

```


